name: Release Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Package version"
        type: "string"
      package_name:
        description: "Package name"
        type: "string"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - uses: oras-project/setup-oras@v1
        name: Setup ORAS CLI

      - name: Setup
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.TEMP_VM_SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

          ssh-keyscan 159.89.175.183 >> $HOME/.ssh/known_hosts
          chmod 644 $HOME/.ssh/known_hosts
      - name: Test SSH connection
        run: |
          if ssh -o BatchMode=yes ziggy@159.89.175.183 "echo ok"; then
            echo "SSH connection successful"
          else
            echo "SSH FAILED!" >&2
            exit 1
          fi

      - name: Publish from workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          VERSION=${{ inputs.tag }} SSH_KEY=$HOME/.ssh/id_rsa PKG_NAME=idt .github/scripts/idt-release.sh

      - name: Publish from release
        if: ${{ github.event_name == 'release' }}
        run: |
          VERSION=${{ github.event.release.tag_name }} SSH_KEY=~/.ssh/id_rsa PKG_NAME=idt .github/scripts/idt-release.sh

      - name: Cleanup
        run: |
          rm -rf ~/.ssh/id_rsa
